# Generated by Django 4.1.4 on 2024-07-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
